import type { Metadata } from "next";
import "./globals.css";
import { NextAuthProvider } from "@digifarm/components/auth-provider";
import { Box } from "@mui/material";
import { AppCustomLayout } from "@digifarm/components/layout/app-custom-layout";

export const metadata: Metadata = {
  title: "Revisao Facil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <AppCustomLayout />
          <Box
            sx={{
              flexGrow: 1,
            }}
          >
            {children}
          </Box>
        </NextAuthProvider>
      </body>
    </html>
  );
}
